#!/usr/bin/env genome-perl
use strict;
use warnings;

BEGIN {
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
};

use above "Genome";
use Data::Dumper;
use Test::More tests => 4;

class Genome::Model::Command::Test {
    is => 'Command::V2',
    has => [
        bucket => { is => 'Text' },
        stick => { is => 'Text' },
        rock => { is => 'Text', is_optional => 1 },
        thing => { is => 'Text', default_value => 'thingy' },
    ]
};

my $cmd = Genome::Model::Command::Test->create();
$cmd->dump_error_messages(0);
$cmd->dump_status_messages(0);

my $missing = join(',', sort $cmd->_missing_parameters({}));
is($missing, "--bucket,--stick", "missing parameters detected");

$missing = join(',', sort $cmd->_missing_parameters({stick => 2}));
is($missing, "--bucket", "missing parameters detected");

$missing = join(',', sort $cmd->_missing_parameters({rock => 1, thing => 'whee', stick => 2}));
is($missing, "--bucket", "missing parameters detected");

ok(!$cmd->_missing_parameters( { bucket => 1, stick => 2} ), "no missing parameters");

done_testing()
