#!/usr/bin/env genome-perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above 'Genome';
use Test::More;
use Genome::Test::Factory::InstrumentData::Solexa;
use Genome::Test::Factory::Model::ImportedReferenceSequence;
use Genome::Test::Factory::Build;
use Genome::Test::Factory::SoftwareResult::User;
use Genome::Test::Data qw(get_test_file);
use Sub::Override;
use Cwd qw(abs_path);

my $pkg = 'Genome::InstrumentData::AlignmentResult::Merged::Speedseq';
use_ok($pkg);

my $test_data_dir = __FILE__.'.d';

my $ref_seq_model = Genome::Test::Factory::Model::ImportedReferenceSequence->setup_object;
my $ref_seq_build = Genome::Test::Factory::Build->setup_object(model_id => $ref_seq_model->id);
use Genome::Model::Build::ReferenceSequence;
my $override = Sub::Override->new(
    'Genome::Model::Build::ReferenceSequence::full_consensus_path',
    sub { return abs_path(get_test_file('NA12878', 'human_g1k_v37_20_42220611-42542245.fasta')); }
);

my $result_users = Genome::Test::Factory::SoftwareResult::User->setup_user_hash(
    reference_sequence_build => $ref_seq_build,
);
my $aligner_index = Genome::Model::Build::ReferenceSequence::AlignerIndex->__define__(
    reference_build => $ref_seq_build,
    aligner_version => 'test',
    aligner_name => 'speedseq',
    aligner_params => undef,
    output_dir => get_test_file('NA12878', File::Spec->join(qw(aligner_index speedseq))),
);
ok($aligner_index, 'Created speedseq aligner index');
$aligner_index->recalculate_lookup_hash;
my $instrument_data = Genome::Test::Factory::InstrumentData::Solexa->setup_object(
    flow_cell_id => '12345ABXX',
    lane => '2',
    subset_name => '2',
    run_name => 'example',
    id => 'NA12878',
);
$instrument_data->bam_path(get_test_file('NA12878', 'NA12878.20slice.30X.bam'));

my $merged_alignment_result = $pkg->create(
    instrument_data => [$instrument_data],
    reference_build => $ref_seq_build,
    picard_version => '1.46',
    samtools_version => 'r963',
    aligner_name => 'speedseq',
    aligner_version => 'test',
    aligner_params => '',
    _user_data_for_nested_results => $result_users,
);
ok($merged_alignment_result, 'Merged alignment result created successfully');
isa_ok($merged_alignment_result, $pkg, 'Merged alignment result is a speedseq alignment');

my $cmp = Genome::Model::Tools::Sam::Compare->execute(
    file1 => $merged_alignment_result->bam_file,
    file2 => File::Spec->join($test_data_dir, 'merged_alignment_result.bam'),
);
ok($cmp->result, 'Merged bam as expected');

ok(-e $merged_alignment_result->bam_md5_path, 'md5 file exists');

done_testing;
