#!/usr/bin/env genome-perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;

my $pkg = 'Genome::Qc::Tool::Picard::CollectGcBiasMetrics';
use_ok($pkg);

my $data_dir = __FILE__.".d";

my $summary_output = File::Spec->join($data_dir, 'output_file.txt');

my $tool = $pkg->create(
    gmt_params => {
        input_file => __FILE__,
        refseq_file => __FILE__,
        output_file => __FILE__,
        summary_output => $summary_output,
        temp_directory => __FILE__,
        use_version => 1.123,
    }
);
ok($tool->isa($pkg), 'Tool created successfully');

my @expected_cmd_line =(
    'java',
    '-Xmx4096m',
    '-XX:MaxPermSize=64m',
    '-cp',
    '/usr/share/java/ant.jar:/gscmnt/sata132/techd/solexa/jwalker/lib/picard-tools-1.123/CollectGcBiasMetrics.jar',
    'net.sf.picard.analysis.CollectGcBiasMetrics',
    'CHART_OUTPUT=GC_bias_chart.pdf',
    sprintf('INPUT=%s', __FILE__),
    'MAX_RECORDS_IN_RAM=500000',
    'MINIMUM_GENOME_FRACTION=1.0E-5',
    sprintf('OUTPUT=%s', __FILE__),
    sprintf('REFERENCE_SEQUENCE=%s', __FILE__),
    sprintf('SUMMARY_OUTPUT=%s', $summary_output),
    sprintf('TMP_DIR=%s', __FILE__),
    'VALIDATION_STRINGENCY=SILENT',
    'WINDOW_SIZE=100',
);
is_deeply([$tool->cmd_line], [@expected_cmd_line], 'Command line list as expected');

my %expected_metrics = (
    'at_drop_out' => 11.010202,
    'gc_drop_out' => 0.791313,
);
is_deeply({$tool->get_metrics}, {%expected_metrics}, 'Parsed metrics as expected');

done_testing;
