#!/usr/bin/env genome-perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;
use Sub::Override;
use Genome::Test::Factory::InstrumentData::Solexa;
use Genome::Test::Factory::InstrumentData::AlignmentResult;
use Cwd qw(abs_path);
use JSON qw(encode_json);

my $pkg = 'Genome::Qc::Tool::Picard::CollectGcBiasMetrics';
use_ok($pkg);

my $data_dir = __FILE__.".d";

use Genome::Qc::Tool;
my $sample_name_override = Sub::Override->new(
    'Genome::Qc::Tool::sample_name',
    sub { return 'TEST-patient1-somval_tumor1'; },
);

my $instrument_data = Genome::Test::Factory::InstrumentData::Solexa->setup_object(
    flow_cell_id => '12345ABXX',
    lane => '2',
    subset_name => '2',
    run_name => 'example',
    id => 'NA12878',
);
my $alignment_result = Genome::Test::Factory::InstrumentData::AlignmentResult->setup_object(
    instrument_data => $instrument_data,
);

my $bam_file = abs_path(File::Spec->join($data_dir, 'speedseq_merged.bam'));
my $reference_fasta = abs_path(File::Spec->join($data_dir, 'reference.fasta'));
my $temp_file = Genome::Sys->create_temp_file_path;
my $temp_directory = Genome::Sys->create_temp_file_path;

my $config = {
    picard_collect_gc_bias_metrics => {
        class => 'Genome::Qc::Tool::Picard::CollectGcBiasMetrics',
        params => {
            input_file => $bam_file,
            refseq_file => $reference_fasta,
            assume_sorted => 1,
            use_version => 1.123,
            output_file=> $temp_file,
            chart_output => $temp_file,
            temp_directory => $temp_directory,
        },
    },
};

my $qc_config_name = 'testing-qc-run';
my $qc_config_item = Genome::Qc::Config->create(
    name => $qc_config_name,
    type => 'wgs',
    config => encode_json($config),
);

my $command = Genome::Qc::Run->create(
    config_name => $qc_config_name,
    alignment_result => $alignment_result,
    %{Genome::Test::Factory::SoftwareResult::User->setup_user_hash},
);
ok($command->execute, "Command executes ok");

my %tools = $command->output_result->_tools;
my ($tool) = values %tools;
ok($tool->isa($pkg), 'Tool created successfully');

my $output = $tool->qc_metrics_file;
my @expected_cmd_line =(
    'java',
    '-Xmx4096m',
    '-XX:MaxPermSize=64m',
    '-cp',
    '/usr/share/java/ant.jar:/usr/share/java/picard-tools1.123/CollectGcBiasMetrics.jar',
    'picard.analysis.CollectGcBiasMetrics',
    'ASSUME_SORTED=true',
    sprintf('CHART_OUTPUT=%s', $temp_file),
    sprintf('INPUT=%s', $bam_file),
    'MAX_RECORDS_IN_RAM=500000',
    'MINIMUM_GENOME_FRACTION=1.0E-5',
    sprintf('OUTPUT=%s', $temp_file),
    sprintf('REFERENCE_SEQUENCE=%s', $reference_fasta),
    sprintf('SUMMARY_OUTPUT=%s', $output),
    sprintf('TMP_DIR=%s', $temp_directory),
    'VALIDATION_STRINGENCY=SILENT',
    'WINDOW_SIZE=100',
);
is_deeply([$tool->cmd_line], [@expected_cmd_line], 'Command line list as expected');

my %expected_metrics = (
    'ALIGNED_READS' => '34',
    'AT_DROPOUT' => '34.434797',
    'GC_DROPOUT' => '6.214977',
    'TOTAL_CLUSTERS' => '18',
    'WINDOW_SIZE' => '100',
);
is_deeply({$command->output_result->get_metrics}, {%expected_metrics}, 'Parsed metrics as expected');

done_testing;
