#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use File::Path;
use File::Temp;
use Test::More;
use File::Compare;
use above 'Genome';

my $archos = `uname -a`;
if ($archos !~ /64/) {
    plan skip_all => "Must run from 64-bit machine";
} else {
    plan tests => 4;
}

use_ok('Genome::Model::Tools::CopyNumber::CnvSeg');

my $test_data =  $ENV{GENOME_TEST_INPUTS} . "/Genome-Model-Tools-CopyNumber-CnvSeg";

my $tmpbase = File::Temp::tempdir('CnvSegXXXXX', DIR => "$ENV{GENOME_TEST_TEMP}/", CLEANUP => 1);
my $output_file = "$tmpbase/cnv-seg-output.cnvseg";
my $refbuild_id = 101947881;
my $expected_output = $test_data."/expected_v1/chr22.luc1t.bam.bam2cn.cnvseg";
my $cn_file = $test_data."/chr22.luc1t.bam.bam2cn";
my $min_markers = 3;

my $cnv_seg = Genome::Model::Tools::CopyNumber::CnvSeg->create(
                    copy_number_file => $cn_file,
                    output_file => $output_file,
                    min_markers => $min_markers,
                    gap_file => Genome::Sys->dbpath("tgi-misc-annotation","human-build36-20130113") . "/gaps.csv",
                    centromere_file => Genome::Sys->dbpath("tgi-misc-annotation","human-build36-20130113") . "/centromere.csv",
                );


ok($cnv_seg, 'gmt copy-number bam-to-cn command created');

my $rv = $cnv_seg->execute;

is($rv, 1, 'Testing for successful execution.  Expecting 1.  Got: '.$rv);
print $output_file." ".$expected_output."\n";
my $result = `diff $output_file $expected_output`;
is($result, '', 'Output was identical to expected output.');
