#!/usr/bin/env genome-perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;
use Test::Exception;
use Genome::File::Vcf::Entry;

my $pkg = 'Genome::VariantReporting::Filter::MinFpkm';
use_ok($pkg);
subtest "with fpkm" => sub {
    my $interpreter = $pkg->create(sample_name => 'S1', min_fpkm => 2);
    lives_ok(sub {$interpreter->validate}, "Filter validates");

    my %expected_return_values = (
        C => 0,# fpkm => "1.25"
        G => 0,# fpkm => undef
    );
    my $entry = create_entry_with_fpkm();
    is_deeply({$interpreter->filter_entry($entry)}, \%expected_return_values, "Entry gets interpreted correctly");
};

subtest "with fpkm heterozygous, non-reference genotype" => sub {
    my $interpreter = $pkg->create(sample_name => 'S1', min_fpkm => 2);
    lives_ok(sub {$interpreter->validate}, "Filter validates");

    my %expected_return_values = (
        C => 1,# fpkm => "2.45"
        G => 0,# fpkm => "1.25"
    );
    my $entry = create_entry_with_fpkm_het_no_ref();
    is_deeply({$interpreter->filter_entry($entry)}, \%expected_return_values, "Entry gets interpreted correctly");
};


subtest "without fpkm" => sub {
    my $interpreter = $pkg->create(sample_name => 'S1', min_fpkm => 2);
    lives_ok(sub {$interpreter->validate}, "Filter validates");

    my %expected_return_values = (
        C => 0,# fpkm => '.'
        G => 0,# fpkm => undef
    );
    my $entry = create_entry_without_fpkm();
    is_deeply({$interpreter->filter_entry($entry)}, \%expected_return_values, "Entry gets interpreted correctly");
};
done_testing;

sub create_vcf_header {
    my $header_txt = <<EOS;
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="Passed all filters">
##FILTER=<ID=BAD,Description="This entry is bad and it should feel bad">
##INFO=<ID=A,Number=1,Type=String,Description="Info field A">
##INFO=<ID=C,Number=A,Type=String,Description="Info field C (per-alt)">
##INFO=<ID=E,Number=0,Type=Flag,Description="Info field E">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Depth">
##FORMAT=<ID=FT,Number=.,Type=String,Description="Filter">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S1	S2	S3	S4
EOS
    my @lines = split("\n", $header_txt);
    my $header = Genome::File::Vcf::Header->create(lines => \@lines);
    return $header
}

sub create_entry_with_fpkm_het_no_ref {
    return create_entry("GT:DP:FPKM","1/2:12:2.45,1.25");
}

sub create_entry_with_fpkm {
    return create_entry("GT:DP:FPKM","0/1:12:.,1.25");
}

sub create_entry_without_fpkm {
    return create_entry("GT:DP","0/1:12");
}

sub create_entry {
    my @sample_fields = @_;

    my @fields = (
        '1',            # CHROM
        10,             # POS
        '.',            # ID
        'A',            # REF
        'C,G',            # ALT
        '10.3',         # QUAL
        'PASS',         # FILTER
        'A=B;C=8,9;E',  # INFO
        @sample_fields
    );

    my $entry_txt = join("\t", @fields);
    my $entry = Genome::File::Vcf::Entry->new(create_vcf_header(), $entry_txt);
    return $entry;
}
