#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
};

use above 'Genome';

use Test::More;

use_ok('Genome::Model::GenotypeMicroarray::GenotypeFile::FromInstDataReader') or die;
use_ok('Genome::Model::GenotypeMicroarray::Test') or die;

my $instdata = Genome::Model::GenotypeMicroarray::Test->instrument_data();

my $reader = Genome::Model::GenotypeMicroarray::GenotypeFile::FromInstDataReader->create(
    input => $instdata->genotype_file,
);
ok($reader, 'create reader');

my $cnt = 0;
while ( my $genotype = $reader->read ) {
    $cnt++ if %$genotype;
}
is($cnt, 10, 'read 10 genotypes');

done_testing();
