#!/usr/bin/env genome-perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
}

use strict;
use warnings;

use above 'Genome';

use Test::More;

use_ok('Genome::Model::GenotypeMicroarray::OriginalGenotypeReader') or die;
my $original_genotype_file_path = $ENV{GENOME_TEST_INPUTS} . '/GenotypeMicroarray/build/-8888.original';
my $reader = Genome::Model::GenotypeMicroarray::GenotypeFile::ReaderForOldBuildFile->create(
    input => $original_genotype_file_path,
    filters => ['gc_score:min=0.85',],
);
ok($reader, 'create') or die;
is_deeply($reader->headers, [qw/ chromosome	position	alleles	id	sample_id	log_r_ratio	gc_score	cnv_value	cnv_confidence	allele1	allele2 /], 'headers');
my (@genotypes, $cnt);
while ( my $genotype = $reader->read ) {
    push @genotypes, $genotype;
    $cnt++;
}
is($cnt, 6, "Got $cnt genotypes");
is_deeply(\@genotypes, [_expected_genotypes()], 'genotypes match');
is($reader->total, 9, 'genotypes total');
is($reader->filtered, 3, 'genotypes filtered');
is($reader->passed, 6, 'genotypes pass');

done_testing();


sub _expected_genotypes {
    return (
        {
            'log_r_ratio' => '-0.3639',
            'alleles' => 'AG',
            'position' => '752566',
            'allele2' => 'G',
            'cnv_confidence' => 'NA',
            'cnv_value' => '2.0',
            'chromosome' => '1',
            'allele1' => 'A',
            'sample_id' => '2879594813',
            'id' => undef,
            'gc_score' => '0.8931'
        },
        {
            'log_r_ratio' => '-0.0539',
            'alleles' => 'AG',
            'position' => '752721',
            'allele2' => 'G',
            'cnv_confidence' => 'NA',
            'cnv_value' => '2.0',
            'chromosome' => '1',
            'allele1' => 'A',
            'sample_id' => '2879594813',
            'id' => undef,
            'gc_score' => '0.9256'
        },
        {
            'log_r_ratio' => '-0.0192',
            'alleles' => 'AG',
            'position' => '798959',
            'allele2' => 'G',
            'cnv_confidence' => 'NA',
            'cnv_value' => '2.0',
            'chromosome' => '1',
            'allele1' => 'A',
            'sample_id' => '2879594813',
            'id' => undef,
            'gc_score' => '0.8729'
        },
        {
            'log_r_ratio' => '0.4694',
            'alleles' => 'CC',
            'position' => '838555',
            'allele2' => 'C',
            'cnv_confidence' => 'NA',
            'cnv_value' => '2.0',
            'chromosome' => '1',
            'allele1' => 'C',
            'sample_id' => '2879594813',
            'id' => undef,
            'gc_score' => '0.8749'
        },
        {
            'log_r_ratio' => '0.0389',
            'alleles' => 'AA',
            'position' => '854250',
            'allele2' => 'A',
            'cnv_confidence' => 'NA',
            'cnv_value' => '2.0',
            'chromosome' => '1',
            'allele1' => 'A',
            'sample_id' => '2879594813',
            'id' => undef,
            'gc_score' => '0.8670'
        },
        {
            'log_r_ratio' => '-0.0801',
            'alleles' => 'GG',
            'position' => '882033',
            'allele2' => 'G',
            'cnv_confidence' => 'NA',
            'cnv_value' => '2.0',
            'chromosome' => '1',
            'allele1' => 'G',
            'sample_id' => '2879594813',
            'id' => undef,
            'gc_score' => '0.8677'
        }
    );
}
