#!/usr/bin/env genome-perl

use strict;
use warnings;

use above 'Genome';

use Test::More;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

use_ok('Genome::Model::Command::RenameToDefault') or die;

my @models = map { 
    Genome::Model::DeNovoAssembly->create(
        name => 'RENAME-TEST'.$_,
        subject_name => 'human',
        subject_type => 'species_name',
        processing_profile_id => 2354215,
        center_name => 'wugc',
    );
} (qw/ 1 2 /);
is(@models, 2, 'created models') or die;

my $renamer = Genome::Model::Command::RenameToDefault->create(
    models => \@models,
);
ok($renamer, 'create');
$renamer->dump_status_messages(1);
ok($renamer->execute, 'Execute renamer');
is_deeply([ map { $_->name } @models], [qw/ human.denovo.wugc human.denovo-1.wugc /], 'Renamed models');

done_testing();
exit;

