\documentclass{article}

\usepackage{amsmath}
\usepackage{amscd}
\usepackage[tableposition=top]{caption}
\usepackage{ifthen}
\usepackage[utf8]{inputenc}

\begin{document}

\title{Malachi's Sweave Demo}
\author{Malachi Griffith}
\maketitle

This is a demo for using the Sweave command in R. It will also act as a demo for \LaTeX\ syntax. To get started make a regular \LaTeX\ file (like this one) but give it the suffix \verb@.Rnw@ instead of \verb@.tex@. Then turn it into a (\verb@foo.tex@) file, then \verb@.dvi@ file, then \verb@.pdf@ file with the unix command:
\begin{verbatim}
R CMD Sweave test.Rnw; latex test.tex; dvipdf test.dvi
\end{verbatim}

\begin{tabbing}
In other words, we have a the file chain:
\end{tabbing}
$$
\begin{CD}
   \texttt{test.Rnw}
   @>\texttt{Sweave}>>
   \texttt{test.tex}
   @>\texttt{latex}>>
   \texttt{test.dvi}
   @>\texttt{xdvi or dvipdf}>>
   \text{view of document or dump to pdf}
\end{CD}
$$

\begin{tabbing}
Now lets try some simple R commands.  These get embedded in the \verb@.Rnw@ file as:
\end{tabbing}
\begin{tabbing}
\verb@<<R code block name, options>>@\\
\verb@Block of plain old R code@\\
\verb+@+\\
\end{tabbing}

Figure~\ref{fig:one} (p.~\pageref{fig:one}) 
\verb@and@
Figure~\ref{fig:two} (p.~\pageref{fig:two}) 
show figures for the two sets of distributions plotted against each other:

\pagebreak
<<label=runif, echo=FALSE>>=
x1=runif(100, min=0, max=1)
y1=runif(100, min=0, max=1)
summary(x1)
summary(y1)
@
<<label=fig1plot,include=FALSE>>=
plot(x1, y1, col="blue", pch=16)
@
\begin{figure}[placement h]
\begin{center}
<<label=fig1,fig=TRUE,echo=FALSE>>=
<<fig1plot>>
@
\end{center}
\caption{Scatter Plot of two random uniform sets of n=100, 0 to 1}
\label{fig:one}
\end{figure}

\pagebreak
<<label=rnorm, echo=FALSE>>=
x2=rnorm(250, mean=0.5, sd=1)
y2=rnorm(250, mean=0.5, sd=1)
summary(x2)
summary(y2)
@
<<label=fig2plot,include=FALSE>>=
plot(x2, y2, col="red", pch=16)
abline(h=0, col="black", lty=2)
abline(v=0, col="black", lty=2)
@
\begin{figure}[placement h]
\begin{center}
<<label=fig2,fig=TRUE,echo=FALSE>>=
<<fig2plot>>
@
\end{center}
\caption{Scatter Plot of two random normal sets of n=100, 0 to 1}
\label{fig:two}
\end{figure}










\end{document}
