#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use above 'Genome';
use Test::Exception;
use Test::More;
use Genome::VariantReporting::Suite::BamReadcount::TestHelper qw( create_default_entry
     create_deletion_entry);

my $pkg = 'Genome::VariantReporting::Suite::BamReadcount::MinCoverageObservedInterpreter';
use_ok($pkg);
my $factory = Genome::VariantReporting::Framework::Factory->create();
isa_ok($factory->get_class('interpreters', $pkg->name), $pkg);

my $interpreter = $pkg->create(sample_names => ["S1", "S2", "S3"]);
lives_ok(sub {$interpreter->validate}, "Filter validates");
my $entry = create_default_entry();

subtest 'all alt alleles' => sub {
    my %expected_return_values = (
        G => {
            min_coverage_observed =>  344,
        },
        C => {
            min_coverage_observed =>  4,
        },
        AA => {
            min_coverage_observed =>  23,
        },
    );

    is_deeply({$interpreter->interpret_entry($entry, ['G', 'C', 'AA'] )}, \%expected_return_values, "Entry gets interpreted correctly");
};

done_testing();
