#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{NO_LSF} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

use above 'Genome';
use Genome::SoftwareResult;
use Genome::Utility::Test qw(compare_ok);
use Genome::Test::Factory::SoftwareResult::User;

use Test::More;
use File::Compare;

my $archos = `uname -a`;
if ($archos !~ /64/) {
    plan skip_all => "Must run from 64-bit machine";
}

use_ok('Genome::Model::Tools::DetectVariants2::Squaredancer');

my $refbuild_id = 101947881;
my $ref_seq_build = Genome::Model::Build::ImportedReferenceSequence->get($refbuild_id);
ok($ref_seq_build, 'human36 reference sequence build') or die;

my $test_dir = $ENV{GENOME_TEST_INPUTS} . '/Genome-Model-Tools-DetectVariants2-Squaredancer';
my $test_base_dir = File::Temp::tempdir('DetectVariants2-Squaredancer-XXXXX', CLEANUP => 1, TMPDIR => 1);
my $test_working_dir = "$test_base_dir/output";

my $normal_bam = $test_dir . '/normal.bam';
my $tumor_bam  = $test_dir . '/tumor.bam';
my $bd_cfg     = $test_dir . '/breakdancer_config';

my $chromosome = 22;
my $expected_output = join "/", ($test_dir, 'Squaredancer.out');
my $test_out   = $test_working_dir . '/svs.hq';

my $version = '0.1';
note("use squaredancer version: $version");

my $result_users = Genome::Test::Factory::SoftwareResult::User->setup_user_hash(
    reference_sequence_build => $ref_seq_build,
);

my $command = Genome::Model::Tools::DetectVariants2::Squaredancer->create(
    reference_build_id => $refbuild_id,
    aligned_reads_input => $tumor_bam,
    control_aligned_reads_input => $normal_bam,
    version => $version,
    config_file => $bd_cfg,
    output_directory => $test_working_dir,
    result_users => $result_users,
);

ok($command, 'Created `gmt detect-variants2 squaredancer` command');
$command->dump_status_messages(1);
ok($command->execute, 'Executed `gmt detect-variants2 squaredancer` command');

my $exclude_path_column = sub {
    my $line = shift;
    my @fields = split(/\t/, $line);
    my @included_fields;
    my @columns = grep { $_ !~ /^10$/ } (0..$#fields);
    return join("\t", @fields[@columns]);
};
compare_ok($test_out, $expected_output, name => "svs.hq output as expected",
    filters => [$exclude_path_column, qr/^#.*/],
);

done_testing();
