#!/gsc/bin/perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;
use Genome::Utility::Test qw(compare_ok);

my $class = "Genome::Model::Tools::Gatk::RealignerTargetCreator";

use_ok($class);

my $version = "v1";
my $data_dir = Genome::Utility::Test->data_dir_ok($class, $version);

my $in = $data_dir."/in.bam";
my $expected_out = $data_dir."/expected.intervals";
my $reference = $data_dir."/reference.fasta";
my $out = Genome::Sys->create_temp_file_path;

my $cmd = $class->create(
    input_bam => $in,
    reference_fasta => $reference,
    output_intervals => $out,
);

ok($cmd, "Command was created correctly");
ok($cmd->execute, "Command was executed successfuly");
ok(-s $out, "Output file exists");
compare_ok($out, $expected_out, "Output file was as expected");

done_testing;
