#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
}

use above 'Genome';

use Test::More tests => 3;

use_ok('Genome::Model::Command::Services::AssignQueuedInstrumentData') or die('Cannot continue.');

no warnings;
*Genome::InstrumentDataAttribute::get = sub { return; };
use warnings;

my $command = Genome::Model::Command::Services::AssignQueuedInstrumentData->create;
isa_ok($command, 'Genome::Model::Command::Services::AssignQueuedInstrumentData');
$command->dump_status_messages(1);
ok($command->execute(), 'assign-queued-instrument-data executed successfully.');
