#!/gsc/bin/perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;

use_ok("Genome::Model::Tools::Annovar::AnnotateVariation");

my $test_dir = "/gsc/var/cache/testsuite/data/Genome-Model-Tools-Annovar-AnnotateVariants/v1";

my $temp_dir = Genome::Sys->create_temp_directory;

my $cmd = Genome::Model::Tools::Annovar::AnnotateVariation->create(
    input_file => $test_dir."/input.vcf",
    buildver => "hg19",
    table_names => ["wgEncodeRegDnaseClustered","bed"],
    outfile => $temp_dir."/expected_output",
    annotation_type => "regionanno",
    scorecolumn => 5,
    bedfiles => [$test_dir."/sample.bed", $test_dir."/sample2.bed"],
);
ok($cmd, "Created command");
my $rv = $cmd->execute;
ok($rv, "Executed command successfully");

my $expected_output_prefix = $test_dir."/expected_output";
foreach my $expected_file (("hg19_wgEncodeRegDnaseClustered", "hg19_bed_sample", "hg19_bed_sample2")) {
    ok(-e "$temp_dir/expected_output.$expected_file", "$expected_file exists");
    my $diff_output = `diff $temp_dir/expected_output.$expected_file $test_dir/expected_output.$expected_file`;
    ok(!$diff_output, "No diffs for expected_output.$expected_file") or diag("diff results\n". $diff_output);
}

done_testing;
