$dbd_oracle_mm_opts = {
                        'META_MERGE' => {
                                          'build_requires' => {
                                                                'ExtUtils::MakeMaker' => 0,
                                                                'DBI' => '1.51'
                                                              },
                                          'configure_requires' => {
                                                                    'DBI' => '1.51'
                                                                  }
                                        },
                        'LIBS' => [
                                    '-L/opt/oracle-instantclient-11.2 -lclntsh'
                                  ],
                        'DIR' => [],
                        'OBJECT' => '$(O_FILES)',
                        'EXE_FILES' => [
                                         'ora_explain'
                                       ],
                        'ABSTRACT_FROM' => 'Oracle.pm',
                        'NAME' => 'DBD::Oracle',
                        'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                        'INC' => '-I/opt/oracle-instantclient-11.2/sdk/include -I/usr/lib/perl5/auto/DBI',
                        'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"11.2.0.3\\" -DORA_OCI_102 -DORA_OCI_112',
                        'dist' => {
                                    'DIST_DEFAULT' => 'clean distcheck disttest tardist',
                                    'COMPRESS' => 'gzip -v9',
                                    'PREOP' => '$(MAKE) -f Makefile.old distdir',
                                    'SUFFIX' => 'gz'
                                  },
                        'dynamic_lib' => {
                                           'OTHERLDFLAGS' => ''
                                         },
                        'clean' => {
                                     'FILES' => 'xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def ora_explain mk.pm DBD_ORA_OBJ.*'
                                   },
                        'VERSION_FROM' => 'Oracle.pm',
                        'PREREQ_PM' => {
                                         'DBI' => '1.51'
                                       },
                        'LICENSE' => 'perl'
                      };
$dbd_oracle_mm_self = bless( {
                               'BSLOADLIBS' => '',
                               'ECHO_N' => 'echo -n',
                               'BOOTDEP' => '',
                               'INSTALLSITESCRIPT' => '$(INSTALL_BASE)/bin',
                               'CCDLFLAGS' => '-Wl,-E',
                               'LDDLFLAGS' => '-shared -O2 -g -L/usr/local/lib -fstack-protector',
                               'DESTINSTALLVENDORMAN3DIR' => '$(DESTDIR)$(INSTALLVENDORMAN3DIR)',
                               'LDLOADLIBS' => '-L/opt/oracle-instantclient-11.2 -lclntsh',
                               'PREOP' => '$(NOECHO) $(NOOP)',
                               'MACROSTART' => '',
                               'XS_VERSION' => '1.28',
                               'PERL_MALLOC_DEF' => '-DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc',
                               'MAKEMAKER' => '/gscuser/nnutter/lib/perl5/ExtUtils/MakeMaker.pm',
                               'USEMAKEFILE' => '-f',
                               'RM_RF' => 'rm -rf',
                               'PMLIBDIRS' => [
                                                'lib'
                                              ],
                               'INST_LIBDIR' => '$(INST_LIB)/DBD',
                               'SITEARCHEXP' => '/usr/local/lib/perl/5.10.1',
                               'ABSTRACT' => 'Oracle database driver for the DBI module',
                               'INST_MAN1DIR' => 'blib/man1',
                               'MAN3EXT' => '3pm',
                               'XS' => {
                                         'Oracle.xs' => 'Oracle.c'
                                       },
                               'MAKE' => 'make',
                               'FULL_AR' => '/usr/bin/ar',
                               'TRUE' => 'true',
                               'TEST_REQUIRES' => {},
                               'FULLPERL' => '/usr/bin/perl',
                               'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                               'CONFIG' => [
                                             'ar',
                                             'cc',
                                             'cccdlflags',
                                             'ccdlflags',
                                             'dlext',
                                             'dlsrc',
                                             'exe_ext',
                                             'full_ar',
                                             'ld',
                                             'lddlflags',
                                             'ldflags',
                                             'libc',
                                             'lib_ext',
                                             'obj_ext',
                                             'osname',
                                             'osvers',
                                             'ranlib',
                                             'sitelibexp',
                                             'sitearchexp',
                                             'so',
                                             'vendorarchexp',
                                             'vendorlibexp'
                                           ],
                               'DESTDIR' => '',
                               'MAN1PODS' => {
                                               'ora_explain' => '$(INST_MAN1DIR)/ora_explain.$(MAN1EXT)'
                                             },
                               'INSTALLSITEBIN' => '$(INSTALL_BASE)/bin',
                               'MM_Unix_VERSION' => '6.64',
                               'CHMOD' => 'chmod',
                               'DESTINSTALLVENDORLIB' => '$(DESTDIR)$(INSTALLVENDORLIB)',
                               'OBJ_EXT' => '.o',
                               'C' => [
                                        'Oracle.c',
                                        'dbdimp.c',
                                        'oci8.c'
                                      ],
                               'EXE_FILES' => $dbd_oracle_mm_opts->{'EXE_FILES'},
                               'TARFLAGS' => 'cvf',
                               'PERL_INC' => '/usr/lib/perl/5.10/CORE',
                               'HAS_LINK_CODE' => 1,
                               'INSTALLPRIVLIB' => '$(INSTALL_BASE)/lib/perl5',
                               'SITELIBEXP' => '/usr/local/share/perl/5.10.1',
                               'DESTINSTALLPRIVLIB' => '$(DESTDIR)$(INSTALLPRIVLIB)',
                               'VENDORLIBEXP' => '/usr/share/perl5',
                               'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"11.2.0.3\\" -DORA_OCI_102 -DORA_OCI_112',
                               'FULLEXT' => 'DBD/Oracle',
                               'dynamic_lib' => $dbd_oracle_mm_opts->{'dynamic_lib'},
                               'MAKEFILE' => 'Makefile',
                               'PL_FILES' => {
                                               'ora_explain.PL' => 'ora_explain'
                                             },
                               'SHELL' => '/bin/sh',
                               'VENDORARCHEXP' => '/usr/lib/perl5',
                               'MM_VERSION' => '6.64',
                               'INSTALLSCRIPT' => '$(INSTALL_BASE)/bin',
                               'CC' => 'cc',
                               'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                               'DLEXT' => 'so',
                               'EQUALIZE_TIMESTAMP' => '$(ABSPERLRUN) -MExtUtils::Command -e \'eqtime\' --',
                               'XS_VERSION_MACRO' => 'XS_VERSION',
                               'VERBINST' => 0,
                               'TAR' => 'tar',
                               'ABSPERL' => '$(PERL)',
                               'FALSE' => 'false',
                               'DESTINSTALLARCHLIB' => '$(DESTDIR)$(INSTALLARCHLIB)',
                               'INST_STATIC' => '$(INST_ARCHAUTODIR)/$(BASEEXT)$(LIB_EXT)',
                               'DISTVNAME' => 'DBD-Oracle-1.28',
                               'ABSTRACT_FROM' => 'Oracle.pm',
                               'DESTINSTALLSCRIPT' => '$(DESTDIR)$(INSTALLSCRIPT)',
                               'INST_AUTODIR' => '$(INST_LIB)/auto/$(FULLEXT)',
                               'RESULT' => [
                                             '# This Makefile is for the DBD::Oracle extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.64 (Revision: 66400) from the contents of
# Makefile.PL. Don\'t edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
',
                                             '#   MakeMaker Parameters:
',
                                             '#     ABSTRACT_FROM => q[Oracle.pm]',
                                             '#     AUTHOR => [q[Tim Bunce (dbi-users@perl.org)]]',
                                             '#     BUILD_REQUIRES => {  }',
                                             '#     CONFIGURE_REQUIRES => {  }',
                                             '#     DEFINE => q[ -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"11.2.0.3\\" -DORA_OCI_102 -DORA_OCI_112]',
                                             '#     DIR => []',
                                             '#     EXE_FILES => [q[ora_explain]]',
                                             '#     INC => q[-I/opt/oracle-instantclient-11.2/sdk/include -I/usr/lib/perl5/auto/DBI]',
                                             '#     LIBS => [q[-L/opt/oracle-instantclient-11.2 -lclntsh]]',
                                             '#     LICENSE => q[perl]',
                                             '#     META_MERGE => { build_requires=>{ ExtUtils::MakeMaker=>q[0], DBI=>q[1.51] }, configure_requires=>{ DBI=>q[1.51] } }',
                                             '#     NAME => q[DBD::Oracle]',
                                             '#     OBJECT => q[$(O_FILES)]',
                                             '#     PREREQ_PM => { DBI=>q[1.51] }',
                                             '#     TEST_REQUIRES => {  }',
                                             '#     VERSION_FROM => q[Oracle.pm]',
                                             '#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def ora_explain mk.pm DBD_ORA_OBJ.*] }',
                                             '#     dist => { DIST_DEFAULT=>q[clean distcheck disttest tardist], COMPRESS=>q[gzip -v9], PREOP=>q[$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }',
                                             '#     dynamic_lib => { OTHERLDFLAGS=>q[] }',
                                             '
# --- MakeMaker post_initialize section:'
                                           ],
                               'FULLPERLRUNINST' => '$(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'MAP_TARGET' => 'perl',
                               'INSTALLMAN3DIR' => '$(INSTALL_BASE)/man/man3',
                               'PERLPREFIX' => undef,
                               'INC' => '-I/opt/oracle-instantclient-11.2/sdk/include -I/usr/lib/perl5/auto/DBI',
                               'AUTHOR' => [
                                             'Tim Bunce (dbi-users@perl.org)'
                                           ],
                               'LDFLAGS' => ' -fstack-protector -L/usr/local/lib',
                               'dist' => $dbd_oracle_mm_opts->{'dist'},
                               'INSTALLVENDORMAN1DIR' => '$(INSTALL_BASE)/man/man1',
                               'MAKEFILE_OLD' => 'Makefile.old',
                               'H' => [
                                        'Oracle.h',
                                        'dbdimp.h',
                                        'dbivport.h',
                                        'ocitrace.h'
                                      ],
                               'PERLRUNINST' => '$(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'CI' => 'ci -u',
                               'DESTINSTALLBIN' => '$(DESTDIR)$(INSTALLBIN)',
                               'DESTINSTALLVENDORMAN1DIR' => '$(DESTDIR)$(INSTALLVENDORMAN1DIR)',
                               'INST_ARCHLIBDIR' => '$(INST_ARCHLIB)/DBD',
                               'OBJECT' => '$(O_FILES)',
                               'BUILD_REQUIRES' => {},
                               'NAME_SYM' => 'DBD_Oracle',
                               'RANLIB' => ':',
                               'DIRFILESEP' => '/',
                               'POSTOP' => '$(NOECHO) $(NOOP)',
                               'INSTALLVENDORBIN' => '$(INSTALL_BASE)/bin',
                               'COMPRESS' => 'gzip --best',
                               'SUFFIX' => '.gz',
                               'MAN1EXT' => '1p',
                               'PERL_LIB' => '/usr/share/perl/5.10',
                               'ECHO' => 'echo',
                               'EXPORT_LIST' => '',
                               'INST_BOOT' => '$(INST_ARCHAUTODIR)/$(BASEEXT).bs',
                               'MV' => 'mv',
                               'OSVERS' => '2.6.24-28-server',
                               'LD_RUN_PATH' => '/opt/oracle-instantclient-11.2',
                               'MKPATH' => '$(ABSPERLRUN) -MExtUtils::Command -e \'mkpath\' --',
                               'DESTINSTALLMAN1DIR' => '$(DESTDIR)$(INSTALLMAN1DIR)',
                               'OSNAME' => 'linux',
                               'AR' => 'ar',
                               'O_FILES' => [
                                              'Oracle.o',
                                              'dbdimp.o',
                                              'oci8.o'
                                            ],
                               'FIXIN' => '$(ABSPERLRUN) -MExtUtils::MY -e \'MY->fixin(shift)\' --',
                               'DIST_DEFAULT' => 'tardist',
                               'SKIPHASH' => {},
                               'NOOP' => '$(TRUE)',
                               'PERL_ARCHLIB' => '/usr/lib/perl/5.10',
                               'VERSION_SYM' => '1_28',
                               'VERSION_MACRO' => 'VERSION',
                               'WARN_IF_OLD_PACKLIST' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'warn_if_old_packlist\' --',
                               'MM_REVISION' => 66400,
                               'RM_F' => 'rm -f',
                               'LIBC' => '/lib/libc-2.11.1.so',
                               'UNINST' => 0,
                               'PERLRUN' => '$(PERL)',
                               'LINKTYPE' => 'dynamic',
                               'INSTALLVENDORLIB' => '$(INSTALL_BASE)/lib/perl5',
                               'DEV_NULL' => '> /dev/null 2>&1',
                               'DLSRC' => 'dl_dlopen.xs',
                               'INST_ARCHAUTODIR' => '$(INST_ARCHLIB)/auto/$(FULLEXT)',
                               'DESTINSTALLSITEBIN' => '$(DESTDIR)$(INSTALLSITEBIN)',
                               'MACROEND' => '',
                               'ARGS' => {
                                           'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                                           'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                                           'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                                           'OBJECT' => '$(O_FILES)',
                                           'EXE_FILES' => $dbd_oracle_mm_opts->{'EXE_FILES'},
                                           'ABSTRACT_FROM' => 'Oracle.pm',
                                           'NAME' => 'DBD::Oracle',
                                           'AUTHOR' => $dbd_oracle_mm_self->{'AUTHOR'},
                                           'INC' => '-I/opt/oracle-instantclient-11.2/sdk/include -I/usr/lib/perl5/auto/DBI',
                                           'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"11.2.0.3\\" -DORA_OCI_102 -DORA_OCI_112',
                                           'dist' => $dbd_oracle_mm_opts->{'dist'},
                                           'dynamic_lib' => $dbd_oracle_mm_opts->{'dynamic_lib'},
                                           'clean' => $dbd_oracle_mm_opts->{'clean'},
                                           'INSTALL_BASE' => '/gscuser/nnutter/foobar',
                                           'VERSION_FROM' => 'Oracle.pm',
                                           'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                                           'LICENSE' => 'perl'
                                         },
                               'CP' => 'cp',
                               'DEFINE_VERSION' => '-D$(VERSION_MACRO)=\\"$(VERSION)\\"',
                               'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                               'DESTINSTALLSITELIB' => '$(DESTDIR)$(INSTALLSITELIB)',
                               'INST_LIB' => 'blib/lib',
                               'INST_DYNAMIC' => '$(INST_ARCHAUTODIR)/$(DLBASE).$(DLEXT)',
                               'FULLPERLRUN' => '$(FULLPERL)',
                               'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                               'INSTALLSITEMAN1DIR' => '$(INSTALL_BASE)/man/man1',
                               'DESTINSTALLSITEMAN3DIR' => '$(DESTDIR)$(INSTALLSITEMAN3DIR)',
                               'MOD_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Install -e \'install([ from_to => {@ARGV}, verbose => \'\\\'\'$(VERBINST)\'\\\'\', uninstall_shadows => \'\\\'\'$(UNINST)\'\\\'\', dir_mode => \'\\\'\'$(PERM_DIR)\'\\\'\' ]);\' --',
                               'DLBASE' => '$(BASEEXT)',
                               'INST_MAN3DIR' => 'blib/man3',
                               'CCCDLFLAGS' => '-fPIC',
                               'INSTALLSITEARCH' => '$(INSTALL_BASE)/lib/perl5/x86_64-linux-gnu-thread-multi',
                               'PMLIBPARENTDIRS' => [
                                                      'lib'
                                                    ],
                               'DESTINSTALLSITESCRIPT' => '$(DESTDIR)$(INSTALLSITESCRIPT)',
                               'XS_DEFINE_VERSION' => '-D$(XS_VERSION_MACRO)=\\"$(XS_VERSION)\\"',
                               'SHAR' => 'shar',
                               'PERLMAINCC' => '$(CC)',
                               'RCS_LABEL' => 'rcs -Nv$(VERSION_SYM): -q',
                               'NAME' => 'DBD::Oracle',
                               'PARENT_NAME' => 'DBD',
                               'INSTALLSITELIB' => '$(INSTALL_BASE)/lib/perl5',
                               'MAKE_APERL_FILE' => 'Makefile.aperl',
                               'ZIP' => 'zip',
                               'INSTALL_BASE' => '/gscuser/nnutter/foobar',
                               'VERSION_FROM' => 'Oracle.pm',
                               'LICENSE' => 'perl',
                               'SITEPREFIX' => undef,
                               'INSTALLVENDORSCRIPT' => '$(INSTALL_BASE)/bin',
                               'TO_UNIX' => '$(NOECHO) $(NOOP)',
                               'PERL' => '/usr/bin/perl',
                               'DESTINSTALLVENDORARCH' => '$(DESTDIR)$(INSTALLVENDORARCH)',
                               'NOECHO' => '@',
                               'DESTINSTALLVENDORBIN' => '$(DESTDIR)$(INSTALLVENDORBIN)',
                               'PERM_RW' => 644,
                               'UMASK_NULL' => 'umask 0',
                               'DOC_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'perllocal_install\' --',
                               'TOUCH' => 'touch',
                               'LD' => 'cc',
                               'PERL_SRC' => undef,
                               'DESTINSTALLMAN3DIR' => '$(DESTDIR)$(INSTALLMAN3DIR)',
                               'ZIPFLAGS' => '-r',
                               'PERM_DIR' => 755,
                               'DISTNAME' => 'DBD-Oracle',
                               'INST_BIN' => 'blib/bin',
                               'FIRST_MAKEFILE' => 'Makefile',
                               'VENDORPREFIX' => undef,
                               'LDFROM' => '$(OBJECT)',
                               'clean' => $dbd_oracle_mm_opts->{'clean'},
                               'PREFIX' => '$(INSTALL_BASE)',
                               'INSTALLDIRS' => 'site',
                               'INST_ARCHLIB' => 'blib/arch',
                               'PERL_ARCHIVE' => '',
                               'INSTALLVENDORARCH' => '$(INSTALL_BASE)/lib/perl5/x86_64-linux-gnu-thread-multi',
                               'DESTINSTALLSITEMAN1DIR' => '$(DESTDIR)$(INSTALLSITEMAN1DIR)',
                               'INSTALLBIN' => '$(INSTALL_BASE)/bin',
                               'INSTALLSITEMAN3DIR' => '$(INSTALL_BASE)/man/man3',
                               'PERL_ARCHIVE_AFTER' => '',
                               'MAN3PODS' => {
                                               'Oracle.pm' => '$(INST_MAN3DIR)/DBD::Oracle.$(MAN3EXT)',
                                               'Oraperl.pm' => '$(INST_MAN3DIR)/DBD::Oraperl.$(MAN3EXT)'
                                             },
                               'LIBPERL_A' => 'libperl.a',
                               'INSTALLARCHLIB' => '$(INSTALL_BASE)/lib/perl5/x86_64-linux-gnu-thread-multi',
                               'LIB_EXT' => '.a',
                               'AR_STATIC_ARGS' => 'cr',
                               'INSTALLVENDORMAN3DIR' => '$(INSTALL_BASE)/man/man3',
                               'EXE_EXT' => '',
                               'EXTRALIBS' => '-L/opt/oracle-instantclient-11.2 -lclntsh',
                               'PERM_RWX' => 755,
                               'DESTINSTALLSITEARCH' => '$(DESTDIR)$(INSTALLSITEARCH)',
                               'ABSPERLRUN' => '$(ABSPERL)',
                               'CONFIGURE_REQUIRES' => {},
                               'DESTINSTALLVENDORSCRIPT' => '$(DESTDIR)$(INSTALLVENDORSCRIPT)',
                               'BASEEXT' => 'Oracle',
                               'TEST_F' => 'test -f',
                               'PM' => {
                                         'Oracle.pm' => '$(INST_LIB)/DBD/Oracle.pm',
                                         'oraperl.ph' => '$(INST_LIB)/oraperl.ph',
                                         'lib/DBD/Oracle/Object.pm' => 'blib/lib/DBD/Oracle/Object.pm',
                                         'Oraperl.pm' => '$(INST_LIB)/Oraperl.pm',
                                         'lib/DBD/Oracle/GetInfo.pm' => 'blib/lib/DBD/Oracle/GetInfo.pm',
                                         'mk.pm' => '$(INST_LIB)/DBD/mk.pm'
                                       },
                               'ABSPERLRUNINST' => '$(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'PERL_CORE' => 0,
                               'INSTALLMAN1DIR' => '$(INSTALL_BASE)/man/man1',
                               'SO' => 'so',
                               'VERSION' => '1.28',
                               'DIST_CP' => 'best',
                               'INST_SCRIPT' => 'blib/script',
                               'UNINSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'uninstall\' --'
                             }, 'PACK001' );
