DROP TABLE IF EXISTS citation;
DROP TABLE IF EXISTS drug_gene_interaction_report_attribute;
DROP TABLE IF EXISTS drug_gene_interaction_report;
DROP TABLE IF EXISTS gene_name_report_category_association;
DROP TABLE IF EXISTS gene_name_report_association;
DROP TABLE IF EXISTS drug_name_report_category_association;
DROP TABLE IF EXISTS drug_name_report_association;
DROP TABLE IF EXISTS drug_name_report;
DROP TABLE IF EXISTS gene_name_report;
DROP TABLE IF EXISTS drug_name_group;
DROP TABLE IF EXISTS gene_name_group;
DROP TABLE IF EXISTS drug_name_group_bridge;
DROP TABLE IF EXISTS gene_name_group_bridge;

create table drug_name_report (
        id varchar NOT NULL,
        name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        source_db_name varchar NOT NULL,
        source_db_version varchar NOT NULL,
        PRIMARY KEY (id)
);

create table drug_name_report_association (
        id varchar NOT NULL,
        drug_name_report_id varchar NOT NULL,
        alternate_name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(drug_name_report_id) REFERENCES drug_name_report(id)
);

create table drug_name_report_category_association (
        id varchar NOT NULL,
        drug_name_report_id varchar NOT NULL,
        category_name varchar NOT NULL,
        category_value varchar NOT NULL,
        description text,
        PRIMARY KEY (id),
        FOREIGN KEY(drug_name_report_id) REFERENCES drug_name_report(id)
);

create table gene_name_report (
        id varchar NOT NULL,
        name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        source_db_name varchar NOT NULL,
        source_db_version varchar NOT NULL,
        PRIMARY KEY (id)
);

create table gene_name_report_association (
        id varchar NOT NULL,
        gene_name_report_id varchar NOT NULL,
        alternate_name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(gene_name_report_id) REFERENCES gene_name_report(id)
);

create table gene_name_report_category_association (
        id varchar NOT NULL,
        gene_name_report_id varchar NOT NULL,
        category_name varchar NOT NULL,
        category_value varchar NOT NULL,
        description text,
        PRIMARY KEY (id),
        FOREIGN KEY(gene_name_report_id) REFERENCES gene_name_report(id)
);

create table drug_gene_interaction_report (
        id varchar NOT NULL,
        drug_name_report_id varchar NOT NULL,
        gene_name_report_id varchar NOT NULL,
        interaction_type varchar,
        source_db_name varchar NOT NULL,
        source_db_version varchar NOT NULL,
        description text,
        PRIMARY KEY(id),
        FOREIGN KEY(drug_name_report_id) REFERENCES drug_name_report(id),
        FOREIGN KEY(gene_name_report_id) REFERENCES gene_name_report(id),
        UNIQUE (drug_name_report_id, gene_name_report_id, interaction_type)
);

create table drug_gene_interaction_report_attribute (
        id varchar NOT NULL,
        interaction_id varchar NOT NULL REFERENCES drug_gene_interaction_report(id),
        name varchar NOT NULL,
        value varchar NOT NULL,
        PRIMARY KEY (id)
);

create table citation (
        id varchar NOT NULL,
        source_db_name varchar NOT NULL,
        source_db_version varchar NOT NULL,
        citation text,
        base_url varchar,
        PRIMARY KEY (id)
);

create table gene_name_group (
        id uuid not null,
        name text,
        primary key (id)
);

create table drug_name_group (
        id uuid not null,
        name text,
        primary key (id)
);

create table drug_name_group_bridge (
        drug_name_group_id uuid not null references drug_name_group(id),
        drug_name_report_id uuid not null references drug_name_report(id),
        primary key (drug_name_group_id,drug_name_report_id)
);

create table gene_name_group_bridge (
        gene_name_group_id uuid not null references gene_name_group(id),
        gene_name_report_id uuid not null references gene_name_report(id),
        primary key (gene_name_group_id,gene_name_report_id)
);
