DROP SCHEMA IF EXISTS subject CASCADE;
CREATE SCHEMA subject AUTHORIZATION genome;

SELECT set_config('search_path', current_setting('search_path')  || ', subject', false);
ALTER USER genome SET search_path FROM current;

CREATE TABLE subject.misc_note (
    editor_id          varchar(200) NOT NULL,
    entry_date         timestamp(6) NOT NULL,
    subject_class_name varchar(255) NOT NULL,
    subject_id         varchar(255) NOT NULL,
    header_text        varchar(255) NOT NULL,
    body_text          varchar(4000),
    id                 varchar(32) NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX misc_note_subject_index ON subject.misc_note(subject_class_name, subject_id, header_text);
CREATE INDEX misc_note_subject_date_index ON subject.misc_note(entry_date, subject_class_name, subject_id);
CREATE INDEX misc_note_editor_index ON subject.misc_note(editor_id, entry_date);
CREATE INDEX misc_note_body_index ON subject.misc_note(body_text);

CREATE TABLE subject.subject (
    subject_id    varchar(32) NOT NULL,
    subclass_name varchar(255) NOT NULL,
    name          varchar(255),
    PRIMARY KEY (subject_id)
);
CREATE INDEX subject_name_index ON subject.subject(name);

CREATE TABLE subject.subject_attribute (
    subject_id      varchar(32) NOT NULL REFERENCES subject.subject(subject_id),
    attribute_label varchar(64) NOT NULL,
    attribute_value varchar(512) NOT NULL,
    nomenclature    varchar(64) NOT NULL,
    PRIMARY KEY (subject_id, attribute_label, attribute_value, nomenclature)
);
CREATE INDEX subject_attribute_subject_id_index ON subject.subject_attribute(subject_id);
CREATE INDEX subject_attribute_label_index ON subject.subject_attribute(attribute_label);

CREATE TABLE subject.user (
    name     varchar(64),
    email    varchar(255) NOT NULL,
    username varchar(64),
    PRIMARY KEY (email)
);
CREATE INDEX subject_user_username_index ON subject.user(username);
CREATE INDEX subject_user_email_index ON subject.user(email);

CREATE TABLE subject.role (
    id   varchar(32),
    name varchar(64),
    PRIMARY KEY (id),
    UNIQUE (name)
);
CREATE INDEX subject_role_name_index ON subject.role(name);

CREATE TABLE subject.role_member (
    user_email varchar(255) REFERENCES subject.user(email),
    role_id   varchar(32) REFERENCES subject.user_role(id),
    PRIMARY KEY (user_email, role_id)
);

CREATE TABLE subject.project (
    id   varchar(64) NOT NULL,
    name varchar(200) NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX project_name_index ON subject.project(name);

CREATE TABLE subject.project_part (
    id              varchar(64) NOT NULL,
    project_id      varchar(64) NOT NULL REFERENCES subject.project(id),
    part_class_name varchar(256) NOT NULL,
    part_id         varchar(64) NOT NULL,
    label           varchar(100),
    role            varchar(100),
    PRIMARY KEY (id),
    UNIQUE (project_id, part_class_name, part_id)
);
CREATE INDEX project_part_part_role_index ON subject.project_part(part_class_name, part_id, role);
CREATE INDEX project_part_project_role_index ON subject.project_part(project_id, role);
CREATE INDEX project_part_project_label_index ON subject.project_part(project_id, label);

CREATE TABLE subject.misc_attribute (
    entity_class_name varchar(255) NOT NULL,
    entity_id         varchar(1000) NOT NULL,
    property_name     varchar(255) NOT NULL,
    value             varchar(4000) NOT NULL,
    PRIMARY KEY (entity_id, entity_class_name, property_name)
);
CREATE INDEX misc_attribute_entity_class_property_value_index ON subject.misc_attribute(entity_class_name, property_name, value);
