DROP SCHEMA IF EXISTS web CASCADE;
CREATE SCHEMA web AUTHORIZATION genome;

SELECT set_config('search_path', current_setting('search_path') || ', web', false);
ALTER USER genome SET search_path FROM current;

CREATE TABLE web.nomenclature (
    id   varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX nomenclature_name_index ON web.nomenclature(name);

CREATE TABLE web.nomenclature_field (
    id              varchar(255) NOT NULL,
    name            varchar(255) NOT NULL,
    type            varchar(255) NOT NULL,
    nomenclature_id varchar(255) NOT NULL REFERENCES web.nomenclature(id),
    PRIMARY KEY (id)
);
CREATE INDEX nomenclature_field_nomenclature_id_index ON web.nomenclature_field(nomenclature_id);

CREATE TABLE web.nomenclature_enum_value (
    id                    varchar(255) NOT NULL,
    value                 varchar(255) NOT NULL,
    nomenclature_field_id varchar(255) NOT NULL REFERENCES web.nomenclature_field(id),
    PRIMARY KEY (id)
);
CREATE INDEX nomenclature_enum_field_index ON web.nomenclature_enum_value(nomenclature_field_id);

CREATE TABLE web.task (
    id              varchar(255) NOT NULL,
    user_id         varchar(255) NOT NULL,
    command_class   varchar(255) NOT NULL,
    stdout_pathname varchar(4096),
    stderr_pathname varchar(4096),
    status          varchar(50) NOT NULL,
    submit_time     timestamp(6) DEFAULT current_timestamp NOT NULL,
    time_started    timestamp(6),
    time_finished   timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE web.task_params (
    task_id varchar(255) NOT NULL REFERENCES web.task(id),
    params  text NOT NULL,
    PRIMARY KEY (task_id)
);

CREATE TABLE web.search_index_queue (
    id            varchar(32)  NOT NULL,
    subject_id    varchar(256)  NOT NULL,
    subject_class varchar(255) NOT NULL,
    timestamp     timestamp NOT NULL,
    CONSTRAINT SIQ_PK PRIMARY KEY (id)
);
