#!/usr/bin/env genome-perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;

use_ok('Genome::Model::GenePrediction::Command::Eukaryotic::MaskRnaSequence') or die;

my $test_data_dir = $ENV{GENOME_TEST_INPUTS} . '/Genome-Model-GenePrediction-Eukaryotic/';
ok(-d $test_data_dir, "test data dir exists at $test_data_dir") or die;

my $test_output_dir = File::Temp::tempdir('Genome-Model-GenePrediction-Eukaryotic-XXXXX', TMPDIR => 1, CLEANUP => 1);
ok(-d $test_output_dir, "test output dir exists at $test_output_dir");

my $input_fasta = $test_data_dir . "short_ctg.dna";
ok(-e $input_fasta, "input fasta exists at $input_fasta") or die;

my $expected_output = $test_data_dir . "short_ctg.rna_masked.expected";
ok(-e $expected_output, "expected output exists at $expected_output");

my $output_file_fh = File::Temp->new(
    DIR => $test_output_dir,
    TEMPLATE => "egap_mask_rna_XXXXXX",
);
my $output_file = $output_file_fh->filename;
$output_file_fh->close;

my $masker = Genome::Model::GenePrediction::Command::Eukaryotic::MaskRnaSequence->create(
    prediction_directory => $test_data_dir,
    fasta_file => $input_fasta,
    masked_fasta_file => $output_file,
);
ok($masker, 'created rna masking command object') or die;

my $rv = $masker->execute;
ok($rv, 'masker executed successfully');

ok(-s $output_file, "output file $output_file has size");

my $expected_md5 = Genome::Sys->md5sum($expected_output);
my $output_md5 = Genome::Sys->md5sum($output_file);
ok($expected_md5 eq $output_md5, "expected output matches actual output!");

done_testing();
