#!/bin/sh
set -e

# Re-establish symlinks that exist in the original source
ln -s xsltsl-1.2.1 /usr/share/perl5/Genome/xsl/html/common_includes/xsltsl
ln -s TableTools-2.0.1 /usr/share/perl5/Genome/View/Resource/Html/js/pkg/TableTools
ln -s boxy-0.1.4 /usr/share/perl5/Genome/View/Resource/Html/js/pkg/boxy
ln -s dataTables-1.7 /usr/share/perl5/Genome/View/Resource/Html/js/pkg/dataTables

ln -s /lib/init/upstart-job /etc/init.d/genome-task-runner
ln -s /lib/init/upstart-job /etc/init.d/genome-search-index-queue

# Fix a known bug with solr common
ln -sf /usr/share/java/lucene-memory.jar /usr/share/solr/WEB-INF/lib/

# Enable apache mods
a2enmod fastcgi
a2enmod rewrite

# Enable genome apache site
a2ensite genome

# Put genome-www tables into postgres
/usr/bin/sudo -i -u postgres psql -U genome -d genome < /usr/share/perl5/Genome/DataSource/Web.schema.psql

# Restart/start services
service tomcat6 restart
service apache2 restart

# Using service/restart for genome-www doesn't appear to work, so using /etc/init.d/genome-www despite warnings
/etc/init.d/genome-www restart

# dh_installinit takes care of starting the genome-www service but it doesn't do the genome-task-runner
# service. so we've got to do that ourselves here at the end.
service genome-task-runner start
service genome-search-index-queue start
