#!/bin/sh
set -e

# FIXME The version of Web::Simple we require has not been packaged, so this
# is a short-term hack to allow us to use the newest version. When it is 
# properly packaged, it can be added as a dependency in debian/control and
# these lines can be removed
/usr/bin/curl -L http://cpanmin.us | perl - --sudo App::cpanminus
/usr/bin/perl /usr/local/bin/cpanm Web::Simple

exit 0

