#!/bin/sh
set -e

# Remove symlinks that were manually put into place
unlink /usr/share/perl5/Genome/xsl/html/common_includes/xsltsl
unlink /usr/share/perl5/Genome/View/Resource/Html/js/pkg/TableTools
unlink /usr/share/perl5/Genome/View/Resource/Html/js/pkg/boxy
unlink /usr/share/perl5/Genome/View/Resource/Html/js/pkg/dataTables
unlink /usr/share/solr/WEB-INF/lib/lucene-memory.jar
unlink /etc/init.d/genome-task-runner
unlink /etc/init.d/genome-search-index-queue

# Disable genome site
a2dissite genome

# Drop schema from postgres
/bin/echo "DROP SCHEMA web CASCADE" | /usr/bin/sudo -i -u postgres /usr/bin/psql -U genome -d genome

exit 0
