#!/usr/bin/env genome-perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;

use_ok('Genome::Model::Tools::Predictor::StrategyParser') or die;

# Parse a strategy with a single predictor
my $parser = Genome::Model::Tools::Predictor::StrategyParser->create(
    strategy => 'interproscan [params] [version]',
);
my %result = %{$parser->parse};
ok(%result, 'got result from parsing');

my @predictors = sort keys %result;
ok(@predictors == 1, 'got expected number of predictors from parser');
ok($predictors[0] eq 'interproscan', 'got expected predictor name');
ok($result{$predictors[0]}{parameters} eq 'params', 'got expected params');
ok($result{$predictors[0]}{version} eq 'version', 'got expected version');

# Parse a strategy with two predictors
$parser = Genome::Model::Tools::Predictor::StrategyParser->create(
    strategy => 'interproscan [params] [version] union psortb [foo] [bar]',
);
%result = %{$parser->parse};

@predictors = sort keys %result;
ok(@predictors == 2, 'got expected number of predictors from parser');

ok($predictors[0] eq 'interproscan', 'got expected predictor name');
ok($result{$predictors[0]}{parameters} eq 'params', 'got expected params');
ok($result{$predictors[0]}{version} eq 'version', 'got expected version');

ok($predictors[1] eq 'psortb', 'got expected predictor name');
ok($result{$predictors[1]}{parameters} eq 'foo', 'got expected params');
ok($result{$predictors[1]}{version} eq 'bar', 'got expected version');

# Parse a strategy with two predictors that may lack params/version
$parser = Genome::Model::Tools::Predictor::StrategyParser->create(
    strategy => 'interproscan [] [version] union psortb [foo] []',
);
%result = %{$parser->parse};

@predictors = sort keys %result;
ok(@predictors == 2, 'got expected number of predictors from parser');

ok($predictors[0] eq 'interproscan', 'got expected predictor name');
ok($result{$predictors[0]}{parameters} eq '', 'got expected params');
ok($result{$predictors[0]}{version} eq 'version', 'got expected version');

ok($predictors[1] eq 'psortb', 'got expected predictor name');
ok($result{$predictors[1]}{parameters} eq 'foo', 'got expected params');
ok($result{$predictors[1]}{version} eq '', 'got expected version');

done_testing();
