#!/usr/bin/env genome-perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
}

use strict;
use warnings;

use above 'Genome';

require File::Compare;
use Test::More;

use_ok('Genome::Model::Tools::Sx::Sort::ByQual') or die;

# Files
my $dir = $ENV{GENOME_TEST_INPUTS} . '/Genome-Model-Tools-Sx/SortByQual';
my $in_fastq = $dir.'/in.fastq';
ok(-s $in_fastq, 'in fastq');
my $example_fastq = $dir.'/out.fastq';
ok(-s $example_fastq, 'example fastq');

my $tmp_dir = File::Temp::tempdir(CLEANUP => 1);
my $out_fastq = $tmp_dir.'/out.fastq';

# Ok
my $sorter = Genome::Model::Tools::Sx::Sort::ByQual->create(
    input  => [ $in_fastq.':cnt=2' ],
    output => [ $out_fastq ],
);
ok($sorter, 'create by avg qual sorter');
isa_ok($sorter, 'Genome::Model::Tools::Sx::Sort::ByQual');
ok($sorter->execute, 'execute by avg qual sorter');
is(File::Compare::compare($example_fastq, $out_fastq), 0, "sorted as expected");

#print "$tmp_dir\n"; <STDIN>;
done_testing();
exit;

