#! /gsc/bin/perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
}

use strict;
use warnings;

use above 'Genome';

require Genome::Utility::Test;
use Test::More;

my $class = 'Genome::InstrumentData::Gatk::BaseRecalibratorBamResult';
use_ok($class) or die;
my $result_data_dir = Genome::Utility::Test->data_dir_ok($class, 'v1');

# Inputs
use_ok('Genome::InstrumentData::Gatk::Test') or die;
my $gatk_test = Genome::InstrumentData::Gatk::Test->get;
my $bam_source = $gatk_test->bam_source;
my $reference_build = $gatk_test->reference_build;
my $version = '2.4';
my %params = (
    version => $version,
    bam_source => $bam_source,
    reference_build => $reference_build,
    known_sites => [ $gatk_test->known_site ],
);

# Get [fails as expected]
my $base_recalibrator = Genome::InstrumentData::Gatk::BaseRecalibratorBamResult->get_with_lock(%params);
ok(!$base_recalibrator, 'Failed to get existing gatk indel realigner result');

# Create
$base_recalibrator = Genome::InstrumentData::Gatk::BaseRecalibratorBamResult->get_or_create(%params);
ok($base_recalibrator, 'created gatk indel realigner');

# Outputs
ok($base_recalibrator->base_recalibrator_result, 'base recalibrator result');
is($base_recalibrator->bam_path, $base_recalibrator->output_dir.'/'.$base_recalibrator->id.'.bam', 'bam file named correctly');
ok(-s $base_recalibrator->bam_path, 'bam file exists');#bam produced is the same except for the knowns file in the header
ok(-s $base_recalibrator->bam_path.'.bai', 'bam index exists');
ok(-s $base_recalibrator->bam_flagstat_file, 'bam flagstat file exists');
Genome::Utility::Test::compare_ok($base_recalibrator->bam_flagstat_file, $result_data_dir.'/expected.bam.flagstat', 'flagstat matches');
ok(-s $base_recalibrator->bam_md5_path, 'bam md5 path exists');
Genome::Utility::Test::compare_ok(
    $base_recalibrator->bam_md5_path,
    $result_data_dir.'/expected.bam.md5',
    'md5 matches',
    filters => [
        sub{ my $line = shift; $line =~ s/\s+.+//; return $line; }, # extract md5
    ],
);

# User
my $sr_user = $base_recalibrator->base_recalibrator_result->users;
ok($sr_user, 'add user to base recalibrator result');
is($sr_user->label, 'recalibration table', 'sr user has correct label');
my $user = $sr_user->user;
is($user, $base_recalibrator, 'base recalibrator is used by base recalibrator bam result');

# Base recalibrator params
my %base_recalibrator_params = $base_recalibrator->base_recalibrator_params;
is_deeply(
    \%base_recalibrator_params,
    {
        version => $version,
        bam_source => $bam_source,
        reference_build => $reference_build,
        known_sites => [ $gatk_test->known_site ],
    },
    'base recalibrator params',
);

# Get base recalibrator result
ok(!$base_recalibrator->base_recalibrator_result(undef), 'base recalibrator result unset');
ok($base_recalibrator->get_base_recalibrator_result, 'get base recalibrator result');
ok($base_recalibrator->base_recalibrator_result, 'base recalibrator result set');
ok(-s $base_recalibrator->base_recalibrator_result->recalibration_table_file, 'base recalibrator result recalibration table file');

# Allocation params
is(
    $base_recalibrator->resolve_allocation_disk_group_name,
    'info_genome_models',
    'resolve_allocation_disk_group_name',
);
is(
    $base_recalibrator->resolve_allocation_kilobytes_requested,
    160,
    'resolve_allocation_kilobytes_requested',
);
like(
    $base_recalibrator->resolve_allocation_subdirectory,
    qr(^model_data/gatk/base_recalibrator_bam-),
    'resolve_allocation_subdirectory',
);

#print $base_recalibrator->output_dir."\n"; <STDIN>;
done_testing();
