#!/usr/bin/env genome-perl

use strict;
use warnings;

use above "Genome";
use Command;
use Test::More;
plan tests => 10;

use MIME::Base64;
use Data::Dumper;


$ENV{TEST_MODE} = 1;
$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;


my $nom = make_fake_nomenclature();

my $obj1 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(good_data()),
    subclass_name   => 'Genome::Sample',
    project_name    => 'myFakeProject0'
);
ok($obj1, 'create import command object');
cmp_ok($obj1->execute(), '==', 6, 'with good input');
ok(Genome::Project->get(name => 'myFakeProject0'), 'check for project');


my $obj2 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(bad_column_data()),
    subclass_name   => 'Genome::Sample',
    project_name    => 'myFakeProject1'
);
eval { $obj2->execute(); };
ok($@,"with invalid column names");
diag($@);


my $obj3 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(bad_enum_data()),
    subclass_name   => 'Genome::Sample',
    project_name    => 'myFakeProject2'
);
cmp_ok($obj3->execute(), '==', 5, 'with bad enum value');


my $obj4 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(non_unique_data()),
    subclass_name   => 'Genome::Sample',
    project_name    => 'myFakeProject3'
);
eval { $obj4->execute(); };
ok($@, 'with non-unique records');
diag($@);


my $obj5 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(bad_real_data()),
    subclass_name   => 'Genome::Sample',
    project_name    => 'myFakeProject4'
);
cmp_ok($obj5->execute(), '==', 5, 'with bad real value');


my $obj6 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(good_data_with_na()),
    subclass_name   => 'Genome::Sample',
    project_name    => 'myFakeProject5'
);
cmp_ok($obj6->execute(), '==', 6, 'with good data and NA');


my $obj7 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(good_individual_data()),
    subclass_name   => 'Genome::Individual',
    project_name    => 'myFakeProject6'
);
cmp_ok($obj7->execute(), '==', 3, 'with good data at individual level');
# TODO: check that attributes went on sample level


my $obj8 = Genome::Subject::Command::Import->create(
    nomenclature_id => $nom->id,
    content         => MIME::Base64::encode_base64(bad_individual_data()),
    subclass_name   => 'Genome::Individual',
    project_name    => 'myFakeProject7'
);
cmp_ok($obj8->execute(), '==', 3, 'with bad individual');





sub good_data {
    return << "_DATA_";
sample,height,weight,sex
test_sample0,72,200,"male"
test_sample1,60,140,"female"
_DATA_
}

sub good_individual_data {
    return << "_DATA_";
individual,height,weight,sex
TEST-patient1,72,200,"male"
_DATA_
}

sub good_data_with_na {
    return << "_DATA_";
sample,height,weight,sex
test_sample0,"NA",200,"male"
test_sample1,60,140,"female"
_DATA_
}

sub bad_individual_data {
    # specified indivual, uploaded sample
    return << "_DATA_";
individual,height,weight,sex
TEST-patient1,92,222,"male"
test_sample0,72,200,"male"
_DATA_
}

sub bad_column_data {
    return << "_DATA_";
sample,favorite_color,height,weight,sex
test_sample0,red,72,200,"male"
test_sample1,blue,60,140,"female"
_DATA_
}

sub bad_enum_data {
    return << "_DATA_";
sample,height,weight,sex
test_sample0,72,200,"dude"
test_sample1,60,140,"female"
_DATA_
}

sub non_unique_data {
    return << "_DATA_";
sample,height,weight,sex
test_sample0,72,200,"male"
test_sample1,60,140,"female"
test_sample0,12,345,"female"
_DATA_
}

sub bad_real_data {
    return << "_DATA_";
sample,height,weight,sex
test_sample0,"tall",200,"male"
test_sample1,60,140,"female"
_DATA_
}

sub make_fake_nomenclature {

    my $n = Genome::Nomenclature->create( 
        name => 'TEST_NOMENCLATURE',
        empty_equivalent => 'NA'
    );

    Genome::Nomenclature::Field->create(
        name => 'height',
        type => 'real',
        nomenclature_id => $n->id
    );
    Genome::Nomenclature::Field->create(
        name => 'weight',
        type => 'real',
        nomenclature_id => $n->id
    );
    my $enum_field = Genome::Nomenclature::Field->create(
        name => 'sex',
        type => 'enumerated',
        nomenclature_id => $n->id,
    );
    Genome::Nomenclature::Field::EnumValue->create( nomenclature_field_id => $enum_field->id, value => 'male');
    Genome::Nomenclature::Field::EnumValue->create( nomenclature_field_id => $enum_field->id, value => 'female');

    return $n;
}
