#!/usr/bin/env genome-perl

use strict;
use warnings FATAL => 'all';

use Test::More;
use above 'Genome';
use Genome::Utility::Test qw(compare_ok);
use Genome::Annotation::TestHelpers qw(
    get_test_somatic_variation_build
);
use Genome::Annotation::Plan::TestHelpers qw(
    set_what_interpreter_x_requires
);

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

my $pkg = 'Genome::Annotation::BamReadcount::Expert';
use_ok($pkg) || die;

my $VERSION = 1; # Bump this each time test data changes
my $test_dir = Genome::Utility::Test->data_dir($pkg, "v$VERSION");
if (-d $test_dir) {
    note "Found test directory ($test_dir)";
} else {
    die "Failed to find test directory ($test_dir)";
}

set_what_interpreter_x_requires('bam-readcount');
my $build = get_test_somatic_variation_build($VERSION, File::Spec->join($test_dir, 'plan.yaml'));

done_testing();
