#!/bin/bash
set -o errexit

echo "Creating SQLite DBs:"
for DB_TXT in $(find $WORKSPACE -iname '*sqlite3-dump' -or -iname '*sqlite3n-dump'); do
    DB_BIN=${DB_TXT/-dump/}
    rm -f "$DB_BIN"
    sqlite3 "$DB_BIN" < "$DB_TXT"
    echo -e "\t${DB_BIN/$WORKSPACE\//}"
done
echo "Done creating SQLite DBs."
