#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

use above 'Genome';
use Genome::Model::Build::SomaticVariationTestGenerator;
use Test::More tests => 10;

use_ok('Genome::Model::SomaticValidation::Command::ExtractVariantsToValidate');


my $model = Genome::Model::Build::SomaticVariationTestGenerator::setup_test_model;
isa_ok($model, 'Genome::Model::SomaticVariation', 'setup test model');

my $target = &setup_target();
isa_ok($target, 'Genome::FeatureList', 'setup target');

my $extract_variants_cmd = Genome::Model::SomaticValidation::Command::ExtractVariantsToValidate->create(
    model => $model,
    target => $target,
);
isa_ok($extract_variants_cmd, 'Genome::Model::SomaticValidation::Command::ExtractVariantsToValidate', 'created extract-variants-to-validate command');
$extract_variants_cmd->dump_status_messages(1);
ok($extract_variants_cmd->execute, 'executed command');

isa_ok($extract_variants_cmd->snv_variant_list, 'Genome::Model::Tools::DetectVariants2::Result::Manual', 'generated manual result for SNVs');

my $expected_snv_data = <<EOBED
1	23	24	A/T
1	29	30	A/T
1	950	951	A/T
2	101	102	A/T
2	320	321	A/T
2	500	501	A/T
EOBED
;

my $expected_file = Genome::Sys->create_temp_file_path;
Genome::Sys->write_file($expected_file, $expected_snv_data);

my ($produced_snv_file) = glob($extract_variants_cmd->snv_variant_list->output_dir . '/*.bed');

ok(!Genome::Sys->diff_file_vs_file($produced_snv_file, $expected_file), 'manual SNV result matches expected file')
    or diag("diff:\n" . Genome::Sys->diff_file_vs_file($produced_snv_file, $expected_file));

my $extract_variants_cmd2 = Genome::Model::SomaticValidation::Command::ExtractVariantsToValidate->create(
    model => $model,
    target => $target,
    report_only => 1,
);
isa_ok($extract_variants_cmd2, 'Genome::Model::SomaticValidation::Command::ExtractVariantsToValidate', 'created extract-variants-to-validate command');
$extract_variants_cmd2->dump_status_messages(1);
ok($extract_variants_cmd2->execute, 'executed command');

ok(!$extract_variants_cmd2->snv_variant_list, 'did not create variant list in report-only mode');

sub setup_target {
    my $bed_data = <<EOBED
1	10	1000	region1
2	100	3000	region2
EOBED
;
    my $bed_file = Genome::Sys->create_temp_file_path();
    Genome::Sys->write_file($bed_file, $bed_data);
    my $fl = Genome::FeatureList->create(
        name => 'test targets for extract-variants-to-validate',
        file_path => $bed_file,
        file_content_hash => Genome::Sys->md5sum($bed_file),
        format => 'true-BED',
        content_type => 'validation',
    );

    return $fl;
}
