use strict;
use warnings;

use File::Path;
use Test::More;
use Sys::Hostname;

use above 'Genome';

BEGIN {
    if (`uname -a` =~ /x86_64/) {
        plan tests => 26;
    } else {
        plan skip_all => 'Must run on a 64 bit machine';
    }
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
    use_ok('Genome::InstrumentData::Solexa');
}

my $t = BowtieTest->new();
$t->execute();

package BowtieTest;
use base 'Genome::InstrumentData::AlignmentResult::Bowtie_Novocraft_RtgMap::TestBase';

#
# Configuration for the aligner name, etc
#
###############################################################################

# this ought to match the name as seen in the processing profile
sub aligner_name { "bowtie" }
sub library_id { '-1234545' }
sub aligner_params { undef }

