#!/usr/bin/env genome-perl

use strict;
use warnings;

use above "Genome";

use Test::More;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

use_ok('Genome::Site::TGI::Measurable') or die;

## ADD_FILE TESTS ARE IN Sample.t ##
## GET_FILE TESTS ARE IN Sample.t ##

done_testing();
