#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{NO_LSF} = 1;
};

use above "Genome";
use Test::More;

use_ok('Genome::Model::Tools::Varscan::SomaticFilterWorkflow') or die;
my $expected_output_dir = $ENV{"GENOME_TEST_INPUTS"} .
  "Genome-Model-Tools-VarScan-SomaticWorkflowFilter/2015-02-06/";
ok(-e $expected_output_dir,
  "Found test dir: $expected_output_dir") or die;

my $clinseq_model = Genome::Model->get(name => "apipe-test-clinseq-wer");
ok($clinseq_model, "found clinseq model");
my $tumor_bam =
  $clinseq_model->wgs_model->tumor_model->last_succeeded_build->merged_alignment_result->bam_path;
ok($tumor_bam, "found tumor bam");
my $normal_bam =
  $clinseq_model->wgs_model->normal_model->last_succeeded_build->merged_alignment_result->bam_path;
ok($normal_bam, "found normal bam");
my $ref_fa =
  $clinseq_model->wgs_model->normal_model->last_succeeded_build->reference_sequence_build->full_consensus_path('fa');
ok($ref_fa, "found reference fasta");

my $temp_dir = Genome::Sys->create_temp_directory();
$temp_dir = "/gscuser/aramu/test/";
ok($temp_dir, "created temp directory: $temp_dir") or die;

#Run somatic filter.
my $somatic_filter =
  Genome::Model::Tools::Varscan::SomaticFilterWorkflow->create(
    outdir => $temp_dir,
    tumor_bam => $tumor_bam,
    normal_bam => $normal_bam,
    prefix => $expected_output_dir . "varscan.snps",
    reference => $ref_fa,
  );
$somatic_filter->queue_status_messages(1);
$somatic_filter->execute();
done_testing();
