#!/gsc/bin/perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;
use Genome::Utility::Test qw(compare_ok);

my $class = "Genome::Model::Tools::BamUtil::ClipOverlap";

use_ok($class);

my $version = "1";
my $data_dir = Genome::Utility::Test->data_dir_ok($class, $version);

my $in = File::Spec->join($data_dir, "testClipOverlapCoord.sam");
my $expected_out = File::Spec->join($data_dir, "testClipOverlapCoord.expected.sam");
my $out = Genome::Sys->create_temp_file_path;

my $cmd = $class->create(
    input_bam => $in,
    output_bam => $out,
);

ok($cmd, "Command was created correctly");
ok($cmd->execute, "Command was executed successfuly");
ok(-s $out, "Output file exists");
compare_ok($out, $expected_out, "Output file was as expected");

done_testing;
