#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{NO_LSF} = 1;
}

use above 'Genome';
use Test::More;
use Genome::Utility::Test qw(compare_ok);

my $TEST_DATA_VERSION = 1;
my $class = 'Genome::Model::Tools::EpitopePrediction::Pipeline';
use_ok($class);

my $test_dir = Genome::Utility::Test->data_dir_ok($class, $TEST_DATA_VERSION);
my $input_file = File::Spec->join($test_dir, "input.tsv");
my $expected_output = File::Spec->join($test_dir, "parsed_file.all");
my $output_dir = Genome::Sys->create_temp_directory;

my $cmd = $class->create(
    input_tsv_file => $input_file,
    output_directory => $output_dir,
    allele =>'HLA-A02:01',
    epitope_length => 9,
    output_filter => 'all',
    anno_db => 'NCBI-human.ensembl',
    anno_db_version => '67_37l_v2',
);

ok($cmd, "Created a command");

ok($cmd->execute, "Command executed");
$DB::single=1;

compare_ok(File::Spec->join($cmd->output_directory, 'HLA-A02:01.9.netmhc.parsed.all'), $expected_output, "Output file is as expected");

done_testing();
