#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
};

use above 'Genome';

require File::Temp;
require File::Compare;
use Test::More;

use_ok('Genome::Model::GenotypeMicroarray::Command::Extract') or die;

my $testdir = $ENV{GENOME_TEST_INPUTS} . '/GenotypeMicroarray';

my $sample = Genome::Sample->__define__(
    id => -8888,
    name => '__TEST__SAMPLE__',
);
ok($sample, 'create sample');

my $pp = Genome::ProcessingProfile::GenotypeMicroarray->__define__(name => '__TEST_PP__');
ok($pp, 'get genotype microarray pp') or return;

my $model = Genome::Model::GenotypeMicroarray->__define__(
    name => 'Test Genotype Microarray',
    processing_profile => $pp,
    subject => $sample,
);
ok($model, 'create genotype microarray model') or return;

my $build = Genome::Model::Build::GenotypeMicroarray->create(
    model => $model,
    data_directory => $testdir.'/build',
);
ok($build, 'create genotype microarray build');

my $tempdir = File::Temp::tempdir(CLEANUP => 1);
my $output = $tempdir.'/-8888.genotypes';
my $cmd = Genome::Model::GenotypeMicroarray::Command::Extract->create(
    build => $build,
    output => $output.':headers=chromosome,position,alleles:print_headers=0',
    filters => [qw/ gc_score:min=0.7 /],
);
ok($cmd, 'create');
$cmd->dump_status_messages(1);
ok($cmd->execute, 'execute');
is($cmd->genotypes_input, 9, 'genotypes_input');
is($cmd->genotypes_filtered, 0, 'genotypes_filtered');
is($cmd->genotypes_output, 9, 'genotypes_output');
my %expected_alleles = (
    'TC' => 1,
    'AA' => 1,
    'CC' => 2,
    'AG' => 3,
    'TT' => 1,
    'GG' => 1,
);
is_deeply($cmd->alleles, \%expected_alleles, 'allelels');
is(File::Compare::compare($output, $build->genotype_file_path), 0, 'output file matches');

#print "gvimdiff $output ".$build->genotype_file_path."\n"; <STDIN>;
done_testing();
