#!/usr/bin/env genome-perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
};

use above 'Genome';

require Genome::Utility::Test;
require File::Temp;
use Test::More;

use_ok('Genome::Model::GenotypeMicroarray::Command::ExtractToVcf') or die;
use_ok('Genome::Model::GenotypeMicroarray::Test') or die;

my $tmpdir = File::Temp::tempdir(CLEANUP => 1);
my $build = Genome::Model::GenotypeMicroarray::Test::example_build();

# BUILD TO VCF => NO OP
my $output_vcf = $tmpdir.'/genotypes.vcf';
my $extract = Genome::Model::GenotypeMicroarray::Command::ExtractToVcf->create(
    build => $build,
    output => $output_vcf,
);
ok($extract, 'create extract command');
ok($extract->execute, 'execute extract command');
Genome::Utility::Test::compare_ok($output_vcf, $build->original_genotype_vcf_file_path, 'vcf matches');

done_testing();
